server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:

        - id: vacation
          uri: http://localhost:8081
          predicates:
            - Path=/vacations/**, /vacationDaysLefts/**, /vacationDaysStatuses/**, /vacationStatuses/**, /vacationDaysLefts/**
        - id: vacation_websocket
          uri: http://localhost:7081
          predicates:
            - Path=/rsocket/vacations

        - id: schedule
          uri: http://localhost:8082
          predicates:
            - Path=/calendars/**, /searchCalendars/**, /findByUserIds/**
        - id: schedule_websocket
          uri: http://localhost:7082
          predicates:
            - Path=/rsocket/schedules

        - id: employee
          uri: http://localhost:8083
          predicates:
            - Path=/employees/**, /employees/**
        - id: employee_websocket
          uri: http://localhost:7083
          predicates:
            - Path=/rsocket/employees

        
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: vacation
          uri: http://vacation:8080
          predicates:
            - Path=/vacations/**, /vacationDaysLefts/**, /vacationDaysStatuses/**, /vacationStatuses/**, /vacationDaysLefts/**
        - id: schedule
          uri: http://schedule:8080
          predicates:
            - Path=/calendars/**, /searchCalendars/**, /findByUserIds/**
        - id: employee
          uri: http://employee:8080
          predicates:
            - Path=/employees/**, /employees/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
